<p style="font-family: Arial; font-size:3em;color:black;"> Session 5 - K-Means</p>

In [9]:
# For this example, we will use K-Means Clustering Project database from Kaggle (https://www.kaggle.com/faressayah/k-means-clustering-private-vs-public-universities)
# For this project we will attempt to use K-Means Clustering to cluster Universities into to two groups, Private and Public.
# We actually have the labels for this data set, but we will NOT use them for the K-Means clustering algorithm, since that is an unsupervised learning algorithm.
# As we will shortly see, we have a data frame with 777 observations on 18 variables.

'''
Private A factor with levels No and Yes indicating private or public university
Apps Number of applications received
Accept Number of applications accepted
Enroll Number of new students enrolled
Top10perc Pct. new students from top 10% of H.S. class
Top25perc Pct. new students from top 25% of H.S. class
F.Undergrad Number of full-time undergraduates
P.Undergrad Number of parttime undergraduates
Outstate Out-of-state tuition
Room.Board Room and board costs
Books Estimated book costs
Personal Estimated personal spending
PhD Pct. of faculty with Ph.D.â€™s
Terminal Pct. of faculty with a terminal degree
S.F.Ratio Student/faculty ratio
perc.alumni Pct. alumni who donate
Expend Instructional expenditure per student
Grad.Rate Graduation rate
'''

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
df = pd.read_csv('College_Data',index_col=0)

In [13]:
df.head()

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 777 entries, Abilene Christian University to York College of Pennsylvania
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Private      777 non-null    object
 1   Apps         777 non-null    int64
 2   Accept       777 non-null    int64
 3   Enroll       777 non-null    int64
 4   Top10perc    777 non-null    int64
 5   Top25perc    777 non-null    int64
 6   F.Undergrad  777 non-null    int64
 7   P.Undergrad  777 non-null    int64
 8   Outstate     777 non-null    int64
 9   Room.Board   777 non-null    int64
 10  Books        777 non-null    int64
 11  Personal     777 non-null    int64
 12  PhD          777 non-null    int64
 13  Terminal     777 non-null    int64
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64
 16  Expend       777 non-null    int64
 17  Grad.Rate    777 non-null    int64
dtypes: float64(1), int64(16), object(1)
memory usage: 115.3+ KB

In [17]:
df.describe()

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
count,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.00000
mean,3001.638353,2018.804376,779.972973,27.558559,55.796654,3699.907336,855.298584,10440.669241,4357.526384,549.380952,1340.642214,72.660232,79.702703,14.089704,22.743887,9660.171171,65.46332
std,3870.201484,2451.113971,929.176190,17.640364,19.804778,4850.420531,1522.431887,4023.016484,1096.696416,165.105360,677.071454,16.328155,14.722359,3.958349,12.391801,5221.768440,17.17771
min,81.000000,72.000000,35.000000,1.000000,9.000000,139.000000,1.000000,2340.000000,1780.000000,96.000000,250.000000,8.000000,24.000000,2.500000,0.000000,3186.000000,10.00000
25%,776.000000,604.000000,242.000000,15.000000,41.000000,992.000000,95.000000,7320.000000,3597.000000,470.000000,850.000000,62.000000,71.000000,11.500000,13.000000,6751.000000,53.00000
50%,1558.000000,1110.000000,434.000000,23.000000,54.000000,1707.000000,353.000000,9990.000000,4200.000000,500.000000,1200.000000,75.000000,82.000000,13.600000,21.000000,8377.000000,65.00000
75%,3624.000000,2424.000000,902.000000,35.000000,69.000000,4005.000000,967.000000,12925.000000,5050.000000,600.000000,1700.000000,85.000000,92.000000,16.500000,31.000000,10830.000000,78.00000
max,48094.000000,26330.000000,6392.000000,96.000000,100.000000,31643.000000,21836.000000,21700.000000,8124.000000,2340.000000,6800.000000,103.000000,100.000000,39.800000,64.000000,56233.000000,118.00000

In [19]:
df[df['Grad.Rate']>100] # Data cleansing

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
Cazenovia College,Yes,3847,3433,527,9,35,1010,12,9384,4840,600,500,22,47,14.3,20,7697,118

In [21]:
df['Grad.Rate']['Cazenovia College'] = 100

C:\Users\wayne\AppData\Local\Temp\ipykernel_25572\2087630962.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Grad.Rate']['Cazenovia College'] = 100
C:\Users\wayne\AppData\Local\Temp\ipykernel_25572\2087630962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Grad.Rate']['Cazenovia College'] = 100

In [23]:
df[df['Grad.Rate']>100]

Empty DataFrame
Columns: [Private, Apps, Accept, Enroll, Top10perc, Top25perc, F.Undergrad, P.Undergrad, Outstate, Room.Board, Books, Personal, PhD, Terminal, S.F.Ratio, perc.alumni, Expend, Grad.Rate]
Index: []

In [25]:
from sklearn.cluster import KMeans

In [26]:
kmeans = KMeans(n_clusters=2)

In [63]:
#kmeans.fit(df.drop('Private',axis=1))    # we will not (and shall not) use class info, it is available only because this is an exercise and we want to examine the perofmacne of our K-Means algorithm.
#print(kmeans.cluster_centers_) # returns the values of the centroids

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df.drop('Private', axis=1))
kmeans.fit(df_scaled)

print(kmeans.cluster_centers_) # returns the values of the centroids

Cluster_predict=kmeans.predict(df.drop('Private',axis=1))
df['Cluster_predict'] = Cluster_predict
df.head(50)

[[ 1.04483741  1.1393409   1.29652154 -0.18421044 -0.03491801  1.36954032
   1.00742316 -0.79832245 -0.40284591  0.10779281  0.62143575  0.38852228
   0.37552637  0.81645673 -0.68723141 -0.33403106 -0.52582555  0.
  -1.49531327]
 [-0.31502635 -0.34351987 -0.39091102  0.05554083  0.01052804 -0.41292673
  -0.30374568  0.24070024  0.12146108 -0.03250034 -0.18736756 -0.1171424
  -0.11322403 -0.24616786  0.20720545  0.10071288  0.15854037  0.
   0.45084822]]

C:\Users\wayne\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
C:\Users\wayne\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but KMeans was fitted without feature names
  warnings.warn(

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate,Cluster_predict,Cluster_actual
Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60,0,1
Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56,1,1
Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54,1,1
Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59,1,1
Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15,1,1
Albertson College,Yes,587,479,158,38,62,678,41,13500,3335,500,675,67,73,9.4,11,9727,55,1,1
Albertus Magnus College,Yes,353,340,103,17,45,416,230,13290,5720,500,1500,90,93,11.5,26,8861,63,1,1
Albion College,Yes,1899,1720,489,37,68,1594,32,13868,4826,450,850,89,100,13.7,37,11487,73,1,1
Albright College,Yes,1038,839,227,30,63,973,306,15595,4400,300,500,79,84,11.3,23,11644,80,1,1
Alderson-Broaddus College,Yes,582,498,172,21,44,799,78,10468,3380,660,1800,40,41,11.5,15,8991,52,1,1
Alfred University,Yes,1732,1425,472,37,75,1830,110,16548,5406,500,600,82,88,11.3,31,10932,73,1,1
Allegheny College,Yes,2652,1900,484,44,77,1707,44,17080,4440,400,600,73,91,9.9,41,11711,76,1,1
Allentown Coll. of St. Francis de Sales,Yes,1179,780,290,38,64,1130,638,9690,4785,600,1000,60,84,13.3,21,7940,74,1,1
Alma College,Yes,1267,1080,385,44,73,1306,28,12572,4552,400,400,79,87,15.3,32,9305,68,1,1
Alverno College,Yes,494,313,157,23,46,1317,1235,8352,3640,650,2449,36,69,11.1,26,8127,55,1,1
American International College,Yes,1420,1093,220,9,22,1018,287,8700,4780,450,1400,78,84,14.7,19,7355,69,1,1
Amherst College,Yes,4302,992,418,83,96,1593,5,19760,5300,660,1598,93,98,8.4,63,21424,100,1,1
Anderson University,Yes,1216,908,423,19,40,1819,281,10100,3520,550,1100,48,61,12.1,14,7994,59,1,1
Andrews University,Yes,1130,704,322,14,23,1586,326,9996,3090,900,1320,62,66,11.5,18,10908,46,1,1
Angelo State University,No,3540,2001,1016,24,54,4190,1512,5130,3592,500,2000,60,62,23.1,5,4010,34,0,0
Antioch University,Yes,713,661,252,25,44,712,23,15476,3336,400,1100,69,82,11.3,35,42926,48,1,1
Appalachian State University,No,7313,4664,1910,20,63,9940,1035,6806,2540,96,2000,83,96,18.3,14,5854,70,0,0
Aquinas College,Yes,619,516,219,20,51,1251,767,11208,4124,350,1615,55,65,12.7,25,6584,65,1,1
Arizona State University Main campus,No,12809,10308,3761,24,49,22593,7585,7434,4850,700,2100,88,93,18.9,5,4602,48,0,0
Arkansas College (Lyon College),Yes,708,334,166,46,74,530,182,8644,3922,500,800,79,88,12.6,24,14579,54,1,1
Arkansas Tech University,No,1734,1729,951,12,52,3602,939,3460,2650,450,1000,57,60,19.6,5,4739,48,0,0
Assumption College,Yes,2135,1700,491,23,59,1708,689,12000,5920,500,500,93,93,13.8,30,7100,88,1,1
Auburn University-Main Campus,No,7548,6791,3070,25,57,16262,1716,6300,3933,600,1908,85,91,16.7,18,6642,69,0,0
Augsburg College,Yes,662,513,257,12,30,2074,726,11902,4372,540,950,65,65,12.8,31,7836,58,1,1
Augustana College IL,Yes,1879,1658,497,36,69,1950,38,13353,4173,540,821,78,83,12.7,40,9220,71,1,1
Augustana College,Yes,761,725,306,21,58,1337,300,10990,3244,600,1021,66,70,10.4,30,6871,69,1,1
Austin College,Yes,948,798,295,42,74,1120,15,11280,4342,400,1150,81,95,13.0,33,11361,71,1,1
Averett College,Yes,627,556,172,16,40,777,538,9925,4135,750,1350,59,67,22.4,11,6523,48,1,1
Baker University,Yes,602,483,206,21,47,958,466,8620,4100,400,2250,58,68,11.0,21,6136,65,1,1
Baldwin-Wallace College,Yes,1690,1366,662,30,61,2718,1460,10995,4410,1000,1000,68,74,17.6,20,8086,85,1,1
Barat College,Yes,261,192,111,15,36,453,266,9690,4300,500,500,57,77,9.7,35,9337,71,1,1
Bard College,Yes,1910,838,285,50,85,1004,15,19264,6206,750,750,98,98,10.4,30,13894,79,1,1
Barnard College,Yes,2496,1402,531,53,95,2121,69,17926,8124,600,850,83,93,10.3,33,12580,91,1,1
Barry University,Yes,990,784,279,18,45,1811,3144,11290,5360,600,1800,76,78,12.6,11,9084,72,1,1
Baylor University,Yes,6075,5349,2367,34,66,9919,484,6450,3920,600,1346,71,76,18.5,38,7503,72,0,1
Beaver College,Yes,1163,850,348,23,56,878,519,12850,5400,400,800,78,89,12.2,30,8954,73,1,1
Bellarmine College,Yes,807,707,308,39,63,1198,605,8840,2950,750,1290,74,82,13.1,31,6668,84,1,1
Belmont Abbey College,Yes,632,494,129,17,36,709,131,9000,4850,300,2480,78,85,13.2,10,7550,52,1,1
Belmont University,Yes,1220,974,481,28,67,1964,623,7800,3664,650,900,61,61,11.1,19,7614,49,1,1
Beloit College,Yes,1320,923,284,26,54,1085,81,16304,3616,355,715,87,95,11.1,26,12957,69,1,1
Bemidji State University,No,1208,877,546,12,36,3796,824,4425,2700,660,1800,57,62,19.6,16,3752,46,0,0
Benedictine College,Yes,632,620,222,14,24,702,501,9550,3850,350,250,64,84,14.1,18,5922,58,1,1
Bennington College,Yes,519,327,114,25,53,457,2,21700,4100,600,500,35,59,10.1,33,16364,55,1,1
Bentley College,Yes,3466,2330,640,20,60,3095,1533,13800,5510,630,850,87,87,17.5,20,10941,82,1,1
Berry College,Yes,1858,1221,480,37,68,1620,49,8050,3940,350,2375,80,80,16.3,17,10511,63,1,1

In [53]:
def convert_to_binary(cluster):  # converts labels for Private into binary values of 0 and 1
    if cluster=='Yes':
        return 1
    else:
        return 0

In [55]:
df['Cluster_actual'] = df['Private'].apply(convert_to_binary)

In [57]:
df.head(50)

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate,Cluster_predict,Cluster_actual
Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60,1,1
Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56,1,1
Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54,1,1
Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59,1,1
Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15,1,1
Albertson College,Yes,587,479,158,38,62,678,41,13500,3335,500,675,67,73,9.4,11,9727,55,1,1
Albertus Magnus College,Yes,353,340,103,17,45,416,230,13290,5720,500,1500,90,93,11.5,26,8861,63,1,1
Albion College,Yes,1899,1720,489,37,68,1594,32,13868,4826,450,850,89,100,13.7,37,11487,73,1,1
Albright College,Yes,1038,839,227,30,63,973,306,15595,4400,300,500,79,84,11.3,23,11644,80,1,1
Alderson-Broaddus College,Yes,582,498,172,21,44,799,78,10468,3380,660,1800,40,41,11.5,15,8991,52,1,1
Alfred University,Yes,1732,1425,472,37,75,1830,110,16548,5406,500,600,82,88,11.3,31,10932,73,1,1
Allegheny College,Yes,2652,1900,484,44,77,1707,44,17080,4440,400,600,73,91,9.9,41,11711,76,1,1
Allentown Coll. of St. Francis de Sales,Yes,1179,780,290,38,64,1130,638,9690,4785,600,1000,60,84,13.3,21,7940,74,1,1
Alma College,Yes,1267,1080,385,44,73,1306,28,12572,4552,400,400,79,87,15.3,32,9305,68,1,1
Alverno College,Yes,494,313,157,23,46,1317,1235,8352,3640,650,2449,36,69,11.1,26,8127,55,1,1
American International College,Yes,1420,1093,220,9,22,1018,287,8700,4780,450,1400,78,84,14.7,19,7355,69,1,1
Amherst College,Yes,4302,992,418,83,96,1593,5,19760,5300,660,1598,93,98,8.4,63,21424,100,1,1
Anderson University,Yes,1216,908,423,19,40,1819,281,10100,3520,550,1100,48,61,12.1,14,7994,59,1,1
Andrews University,Yes,1130,704,322,14,23,1586,326,9996,3090,900,1320,62,66,11.5,18,10908,46,1,1
Angelo State University,No,3540,2001,1016,24,54,4190,1512,5130,3592,500,2000,60,62,23.1,5,4010,34,1,0
Antioch University,Yes,713,661,252,25,44,712,23,15476,3336,400,1100,69,82,11.3,35,42926,48,1,1
Appalachian State University,No,7313,4664,1910,20,63,9940,1035,6806,2540,96,2000,83,96,18.3,14,5854,70,1,0
Aquinas College,Yes,619,516,219,20,51,1251,767,11208,4124,350,1615,55,65,12.7,25,6584,65,1,1
Arizona State University Main campus,No,12809,10308,3761,24,49,22593,7585,7434,4850,700,2100,88,93,18.9,5,4602,48,1,0
Arkansas College (Lyon College),Yes,708,334,166,46,74,530,182,8644,3922,500,800,79,88,12.6,24,14579,54,1,1
Arkansas Tech University,No,1734,1729,951,12,52,3602,939,3460,2650,450,1000,57,60,19.6,5,4739,48,1,0
Assumption College,Yes,2135,1700,491,23,59,1708,689,12000,5920,500,500,93,93,13.8,30,7100,88,1,1
Auburn University-Main Campus,No,7548,6791,3070,25,57,16262,1716,6300,3933,600,1908,85,91,16.7,18,6642,69,1,0
Augsburg College,Yes,662,513,257,12,30,2074,726,11902,4372,540,950,65,65,12.8,31,7836,58,1,1
Augustana College IL,Yes,1879,1658,497,36,69,1950,38,13353,4173,540,821,78,83,12.7,40,9220,71,1,1
Augustana College,Yes,761,725,306,21,58,1337,300,10990,3244,600,1021,66,70,10.4,30,6871,69,1,1
Austin College,Yes,948,798,295,42,74,1120,15,11280,4342,400,1150,81,95,13.0,33,11361,71,1,1
Averett College,Yes,627,556,172,16,40,777,538,9925,4135,750,1350,59,67,22.4,11,6523,48,1,1
Baker University,Yes,602,483,206,21,47,958,466,8620,4100,400,2250,58,68,11.0,21,6136,65,1,1
Baldwin-Wallace College,Yes,1690,1366,662,30,61,2718,1460,10995,4410,1000,1000,68,74,17.6,20,8086,85,1,1
Barat College,Yes,261,192,111,15,36,453,266,9690,4300,500,500,57,77,9.7,35,9337,71,1,1
Bard College,Yes,1910,838,285,50,85,1004,15,19264,6206,750,750,98,98,10.4,30,13894,79,1,1
Barnard College,Yes,2496,1402,531,53,95,2121,69,17926,8124,600,850,83,93,10.3,33,12580,91,1,1
Barry University,Yes,990,784,279,18,45,1811,3144,11290,5360,600,1800,76,78,12.6,11,9084,72,1,1
Baylor University,Yes,6075,5349,2367,34,66,9919,484,6450,3920,600,1346,71,76,18.5,38,7503,72,1,1
Beaver College,Yes,1163,850,348,23,56,878,519,12850,5400,400,800,78,89,12.2,30,8954,73,1,1
Bellarmine College,Yes,807,707,308,39,63,1198,605,8840,2950,750,1290,74,82,13.1,31,6668,84,1,1
Belmont Abbey College,Yes,632,494,129,17,36,709,131,9000,4850,300,2480,78,85,13.2,10,7550,52,1,1
Belmont University,Yes,1220,974,481,28,67,1964,623,7800,3664,650,900,61,61,11.1,19,7614,49,1,1
Beloit College,Yes,1320,923,284,26,54,1085,81,16304,3616,355,715,87,95,11.1,26,12957,69,1,1
Bemidji State University,No,1208,877,546,12,36,3796,824,4425,2700,660,1800,57,62,19.6,16,3752,46,1,0
Benedictine College,Yes,632,620,222,14,24,702,501,9550,3850,350,250,64,84,14.1,18,5922,58,1,1
Bennington College,Yes,519,327,114,25,53,457,2,21700,4100,600,500,35,59,10.1,33,16364,55,1,1
Bentley College,Yes,3466,2330,640,20,60,3095,1533,13800,5510,630,850,87,87,17.5,20,10941,82,1,1
Berry College,Yes,1858,1221,480,37,68,1620,49,8050,3940,350,2375,80,80,16.3,17,10511,63,1,1

In [59]:
from sklearn.metrics import confusion_matrix

In [61]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df['Cluster_actual'],kmeans.labels_))

[[137  75]
 [532  33]]

In [43]:
# How to improve the clustering performance?

In [49]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df['Cluster_actual'],df['Cluster_predict']))

[[138  74]
 [531  34]]